### ISSUE TITLE
Build succeed , Application TalkTalk has not been registered

### ISSUE THREAD

**Issue by sauchye** [hyochan/talktalk-rn#45]
### Version of talktalk-rn
I clone talktalk-rn master repo, Application TalkTalk has not been registered, but build succeed
```
info ** BUILD SUCCEEDED **


info Installing build/TalkTalk/Build/Products/Debug-iphonesimulator/TalkTalk.app
info Launching com.dooboolab.talktalk
com.dooboolab.talktalk: 76547
```

```
react-native-cli: 2.0.1
react-native: 0.59.3
```

<img width="367" alt="tips" src="https://user-images.githubusercontent.com/4171847/55670489-97c46200-58b7-11e9-9244-10eb2cc1df8c.png">

**Comment by hyochan** [comment]
Try to reset cache and try again.
We've supported script
```
npm run start:reset
```
